<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermintaanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('permintaans')->insert([
            [
                'no_permintaan' => 'KDR202400004',
                'tanggal' => '2024-08-18',
                'kode_rm' => '230261',
                'nama' => 'Rina Marlina',
                'layanan' => 'Pergantian Asuransi',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_permintaan' => 'KDR202400005',
                'tanggal' => '2024-08-19',
                'kode_rm' => '230262',
                'nama' => 'Dedi Pratama',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_permintaan' => 'KDR202400006',
                'tanggal' => '2024-08-20',
                'kode_rm' => '230263',
                'nama' => 'Sari Puspita',
                'layanan' => 'Cetak Ulang Kartu',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_permintaan' => 'KDR202400007',
                'tanggal' => '2024-08-21',
                'kode_rm' => '230264',
                'nama' => 'Ahmad Fauzi',
                'layanan' => 'Pergantian Asuransi',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'no_permintaan' => 'KDR202400008',
                'tanggal' => '2024-08-22',
                'kode_rm' => '230265',
                'nama' => 'Ronaldo Wati',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400009',
                'tanggal' => '2024-08-23',
                'kode_rm' => '230265',
                'nama' => 'Linda',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400010',
                'tanggal' => '2024-08-24',
                'kode_rm' => '230265',
                'nama' => 'Tati',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400011',
                'tanggal' => '2024-08-25',
                'kode_rm' => '230265',
                'nama' => 'Akbar',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas G',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400012',
                'tanggal' => '2024-08-26',
                'kode_rm' => '230265',
                'nama' => 'Manda',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas H',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400013',
                'tanggal' => '2024-08-27',
                'kode_rm' => '230265',
                'nama' => 'Lola',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas I',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400014',
                'tanggal' => '2024-08-28',
                'kode_rm' => '230265',
                'nama' => 'Lala',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas J',
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                'no_permintaan' => 'KDR202400015',
                'tanggal' => '2024-08-29',
                'kode_rm' => '230265',
                'nama' => 'Lala',
                'layanan' => 'Perubahan Data Pasien',
                'nm_penerima' => 'Admin RM',
                'nm_petugas_rm' => 'Petugas K',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}